#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | CodeEngine
// +----------------------------------------------------------------------
// | Copyright 艾邦
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: TaoGe <liangtao.gz@foxmail.com>
// +----------------------------------------------------------------------
// | Date: 2021/4/20 10:28
// +----------------------------------------------------------------------

// vendor
require 'vendor/autoload.php';

use Swoole\Process;
use Swoole\Runtime;
use Swoole\Coroutine;
use V2dmIM\Core\utils\log\Log;
use function Swoole\Coroutine\run;

// 此行代码后，文件操作，sleep，Mysqli，PDO，streams等都变成异步IO，见'一键协程化'章节
Runtime::enableCoroutine();

Log::info('Handle service start time ' . (new DateTime)->format('Y-m-d H:i:s'));
Log::info('PHP version: ' . PHP_VERSION);
Log::info('SWOOLE version: ' . SWOOLE_VERSION);
Log::info('Handle version: ' . V2DMIM_VERSION);

// Swoole\Coroutine\run()见'协程容器'章节
run(function () {
    Log::info('start coroutine run id: ' . Swoole\Coroutine::getCid());

    static $running = true;
    // 收到 SIGTERM信 号关闭服务
    Process::signal(SIGTERM, function () use (&$running) {
        Log::info('收到 SIGTERM 信号关闭服务');
        $running = false;
    });
    for ($c = 10; $c--;) {
        Coroutine::create(function () use (&$running) {
            Log::info('start coroutine cid: ' . Swoole\Coroutine::getCid());
            while ($running) {
                usleep(1000);
            }
        });
    }
});

